### PR TITLE
Flutter upgrade + onMonthPageChanged for JalaliTableCalendar

### PR DESCRIPTION
**Pull request by hrmoh**
سلام
نسخهٔ فلاتر آپگرید شده، مشکلات کامپایلی حل شده و یک رویداد با نام
onMonthPageChanged
به 
JalaliTableCalendar
اضافه شده.

با تشکر

### CODE REVIEW

**Comment by Azare77** [comment]
یه سری تغییرات پوش نشده وجود داره که در صورت عدم تداخل کدت بررسی و در نهایت تایید میشه

**Comment by Azare77** [comment]
There is a bug in your code.
When we change the selected month, there is possibility to two months of changes in your returned result. It causes logical error

**Comment by hrmoh** [comment]
> There is a bug in your code. When we change the selected month, there is possibility to two months of changes in your returned result. It causes logical error

OK! Thanks! I will try to resolve the issue and will inform you of a better solution.

**Comment by Azare77** [comment]
actually i did it before but i don't push it at that time 
i suggest you to wait for next version i will push it today and publish in pub.dev soon

**Comment by hrmoh** [comment]
> actually i did it before but i don't push it at that time i suggest you to wait for next version i will push it today and publish in pub.dev soon

Awesome!

**Pull request closed without merging**
